### ISSUE TITLE
Feature request: supported OS for each terminal emulator

### ISSUE THREAD

**Issue by eric-glb** [smasher164/arewesixelyet#10]
Hello,
First, thanks for this project.
The OS on which terminal emulator runs should also be an useful information for users.
Would it be possible to add this?

**Comment by smasher164** [comment]
So for each terminal, you'd like to see a list of every platform it supports? My guess is it's meant to answer the question "which of these terminals supports OS <osname>?"

I'm unsure about this, because currently the website is just meant to track SIXEL support across terminal emulators. Adding OS support and all would lead it to tracking the general feature sets of each of the terminals.

**Comment by eric-glb** [comment]
Thanks for your answer.
Sorry if i was unclear. It would be useful, for each terminal emulator, to indicate on what OS they run.  
As an example: I'm looking for a decent terminal emulator supporting Sixel **and** running on Windows, and I would like to find easily what these emulators are.
(I would understand if you find this out of the scope of the site).

**Comment by davidak** [comment]
@eric-glb using a search engine, i was able to find these:

https://github.com/microsoft/terminal/issues/448
https://mintty.github.io/
https://wezfurlong.org/wezterm/features.html#available-features
https://github.com/kmiya-culti/RLogin/releases/tag/2.25.1

But maybe consider using Linux if you care about such features.
